#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
declare -a MODULES=()
KEEP_GENERATED_AUDIT="${TEMPORARY_AXIOM_KEEP_GENERATED_AUDIT:-0}"
GENERATED_AUDIT_FILE=""

usage() {
  cat <<'EOF'
Usage:
  ./scripts/run_temporary_axiom_audit.sh --module <Lean.Module> [--module <Lean.Module> ...]

Description:
  Generate a temporary Lean audit entry, import the requested host modules,
  and run #assert_no_temporary_axioms.

Options:
  --module <Lean.Module>   Import this module into the generated audit file.
                           Repeat the option to cover multiple roots/sections.
  --help                   Show this help message.

Environment:
  TEMPORARY_AXIOM_KEEP_GENERATED_AUDIT=1
      Keep the generated audit file for inspection when the command exits.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --module)
      if [[ $# -lt 2 ]]; then
        echo "Missing module name after --module." >&2
        echo "Run with --help to see the expected format." >&2
        exit 1
      fi
      MODULES+=("$2")
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      echo "Run with --help to see the supported options." >&2
      exit 1
      ;;
  esac
done

if [[ ${#MODULES[@]} -eq 0 ]]; then
  echo "Temporary axiom audit requires at least one --module argument." >&2
  echo "Pass your project root module, or repeat --module for each section root that must be loaded." >&2
  exit 1
fi

cleanup_generated_audit() {
  if [[ -n "${GENERATED_AUDIT_FILE}" && -f "${GENERATED_AUDIT_FILE}" && "${KEEP_GENERATED_AUDIT}" != "1" ]]; then
    rm -f "${GENERATED_AUDIT_FILE}"
  fi
}
trap cleanup_generated_audit EXIT

cd "${ROOT_DIR}"
GENERATED_AUDIT_FILE="$(mktemp "${ROOT_DIR}/.temporary_axiom_audit.generated.XXXXXX.lean")"

{
  echo "/- Auto-generated by scripts/run_temporary_axiom_audit.sh. -/"
  echo "import TemporaryAxiomTool.TemporaryAxiom"
  for module_name in "${MODULES[@]}"; do
    echo "import ${module_name}"
  done
  echo
  echo "#assert_no_temporary_axioms"
} > "${GENERATED_AUDIT_FILE}"

echo "Running temporary axiom closure audit"
printf '  modules:\n'
for module_name in "${MODULES[@]}"; do
  printf '    - %s\n' "${module_name}"
done

if ! lake env lean "${GENERATED_AUDIT_FILE}"; then
  echo >&2
  echo "Temporary axiom audit failed." >&2
  echo "Check that the listed modules cover every path that can bring temporary axioms into the environment." >&2
  echo "If a module name is wrong, use its Lean import path such as YourProject.Section3." >&2
  echo "Set TEMPORARY_AXIOM_KEEP_GENERATED_AUDIT=1 to inspect the generated audit file." >&2
  exit 1
fi
